# Generated by Django 5.2.12 on 2026-03-25 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=33)),
                ('age', models.IntegerField()),
                ('gender', models.IntegerField(choices=[(1, 'hh'), (2, '帅'), (3, '???')])),
            ],
        ),
    ]
